# Generated by Django 5.2.12 on 2026-03-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtestdefinition",
            name="panels",
            field=models.ManyToManyField(
                related_name="tests",
                through="catalog.LabTestPanelMembership",
                to="catalog.labtestpanel",
            ),
        ),
        migrations.AlterField(
            model_name="labtestpanelmembership",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="catalog.labtestdefinition",
            ),
        ),
    ]
