# Generated by Django 5.2.12 on 2026-03-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
    ]
