# Generated by Django 5.2.12 on 2026-04-02 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('name', models.CharField(help_text='Full legal / display name of the facility.', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name used in reports and labels.', max_length=80)),
                ('code', models.CharField(help_text="Unique alphanumeric code used in order prefixes and identifiers. e.g. 'HGF', 'LAB01'. Cannot be changed after data is attached.", max_length=30, unique=True)),
                ('facility_type', models.CharField(choices=[('center', 'Center'), ('laboratory', 'Laboratory'), ('platform', 'Platform'), ('other', 'Other')], default='center', max_length=30)),
                ('address', models.JSONField(blank=True, default=dict, help_text='FHIR Address datatype stored as JSON (mirrors Patient.address).')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax / fiscal identifier (CNPJ, NIF, etc.).', max_length=50)),
                ('oid', models.CharField(blank=True, help_text="HL7 OID for this facility, used in FHIR Organization resources and as an identifier system namespace. e.g. '2.16.840.1.113883.3.x'.", max_length=100)),
                ('fhir_organization_id', models.CharField(blank=True, help_text='ID of the corresponding FHIR Organization resource on an external FHIR server, if applicable.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive facilities are hidden from user-facing lists but data is retained.')),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone for report timestamps. e.g. 'America/Sao_Paulo'.", max_length=64)),
                ('enforcement_enabled', models.BooleanField(default=False, help_text='Phase 2: when True AND the global FACILITY_ENFORCEMENT_ENABLEDsetting is True, all queries for this facility are scoped.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent_facility', models.ForeignKey(blank=True, help_text='Parent facility in a multi-branch topology. Null = this facility is a top-level node.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="User's home/default facility. At most one per user.")),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='facilities.facility')),
                ('role_override', models.ForeignKey(blank=True, help_text="Optional per-facility role override. When set, takes precedence over the user's global roles for requests scoped to this facility.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_memberships', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility membership',
                'verbose_name_plural': 'Facility memberships',
                'ordering': ['-is_primary', 'facility__name'],
                'unique_together': {('user', 'facility')},
            },
        ),
    ]
