# Generated by Django 5.2.12 on 2026-03-16 10:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in order forms and labels, e.g. 'SER', 'EDTA'.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "handling_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Storage temperature, transport requirements, etc.",
                    ),
                ),
                (
                    "container_color",
                    models.CharField(
                        blank=True,
                        help_text="Vacutainer/tube cap colour, e.g. 'Red', 'Lavender'.",
                        max_length=50,
                    ),
                ),
                (
                    "minimum_volume_ml",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum required volume in millilitres.",
                        max_digits=6,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Type",
                "verbose_name_plural": "Sample Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. 'grams per decilitre'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="UCUM symbol, e.g. 'g/dL'.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "ucum_code",
                    models.CharField(
                        blank=True,
                        help_text="Official UCUM code if different from symbol.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="If set, this record has been soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(
                        blank=True,
                        help_text="Mandatory reason for deletion (regulatory requirement).",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short alphanumeric code, e.g. 'HEM', 'BIO'.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Category",
                "verbose_name_plural": "Test Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="If set, this record has been soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(
                        blank=True,
                        help_text="Mandatory reason for deletion (regulatory requirement).",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique order code, e.g. 'HGB', 'CREAT'.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("abbreviation", models.CharField(blank=True, max_length=20)),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True,
                        help_text="LOINC code, e.g. '718-7' for Haemoglobin.",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("clinical_notes", models.TextField(blank=True)),
                (
                    "minimum_volume_ml",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric"),
                            ("text", "Free text"),
                            ("coded", "Coded (from value set)"),
                            ("semi_quant", "Semi-quantitative"),
                        ],
                        default="numeric",
                        max_length=20,
                    ),
                ),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "tat_value",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "tat_unit",
                    models.CharField(
                        choices=[
                            ("min", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        default="hours",
                        max_length=10,
                    ),
                ),
                (
                    "critical_tat_value",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "critical_tat_unit",
                    models.CharField(
                        choices=[
                            ("min", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        default="hours",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_fasting", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="catalog.testcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample_types",
                    models.ManyToManyField(
                        blank=True, related_name="tests", to="catalog.sampletype"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Definition",
                "verbose_name_plural": "Test Definitions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("any", "Any / Not specified"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "age_min_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum age in days (inclusive). Null = no lower bound.",
                        null=True,
                    ),
                ),
                (
                    "age_max_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum age in days (exclusive). Null = no upper bound.",
                        null=True,
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=100)),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("text_interpretation", models.TextField(blank=True)),
                (
                    "range_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("therapeutic", "Therapeutic"),
                            ("toxic", "Toxic"),
                            ("critical_low", "Critical Low"),
                            ("critical_high", "Critical High"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="catalog.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Range",
                "verbose_name_plural": "Reference Ranges",
                "ordering": ["test", "gender", "age_min_days"],
            },
        ),
        migrations.CreateModel(
            name="TestMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("instrument", models.CharField(blank=True, max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "precision_cv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coefficient of variation (%) for QC.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "detection_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "linearity_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "linearity_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="catalog.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Method",
                "verbose_name_plural": "Test Methods",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="TestPanel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="If set, this record has been soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(
                        blank=True,
                        help_text="Mandatory reason for deletion (regulatory requirement).",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique order code for this panel.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True,
                        help_text="LOINC panel code for interoperability.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="panels",
                        to="catalog.testcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Panel",
                "verbose_name_plural": "Test Panels",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TestPanelMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="catalog.testpanel",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_memberships",
                        to="catalog.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel Membership",
                "ordering": ["sort_order"],
                "unique_together": {("panel", "test")},
            },
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="panels",
            field=models.ManyToManyField(
                blank=True,
                related_name="tests",
                through="catalog.TestPanelMembership",
                to="catalog.testpanel",
            ),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="catalog.unit",
            ),
        ),
        migrations.AddIndex(
            model_name="testdefinition",
            index=models.Index(fields=["code"], name="catalog_tes_code_03dc8b_idx"),
        ),
        migrations.AddIndex(
            model_name="testdefinition",
            index=models.Index(
                fields=["loinc_code"], name="catalog_tes_loinc_c_3e810b_idx"
            ),
        ),
    ]
