# Generated by Django 5.2.12 on 2026-03-23 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'grams per decilitre'.", max_length=100, unique=True)),
                ('symbol', models.CharField(help_text="UCUM symbol, e.g. 'g/dL'.", max_length=50, unique=True)),
                ('ucum_code', models.CharField(blank=True, help_text='Official UCUM code if different from symbol.', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text="Short code used in order forms and labels, e.g. 'SER', 'EDTA'.", max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('handling_instructions', models.TextField(blank=True, help_text='Storage temperature, transport requirements, etc.')),
                ('container_color', models.CharField(blank=True, help_text="Vacutainer/tube cap colour, e.g. 'Red', 'Lavender'.", max_length=50)),
                ('minimum_volume_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum required volume in millilitres.', max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Sample Type',
                'verbose_name_plural': 'Sample Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text="Short alphanumeric code, e.g. 'HEM', 'BIO'.", max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Test Category',
                'verbose_name_plural': 'Lab Test Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('full_name', models.CharField(blank=True, help_text='Full official name if different from the display name.', max_length=300)),
                ('code', models.CharField(help_text="Unique order code, e.g. 'HGB', 'CREAT'.", max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('loinc_code', models.CharField(blank=True, help_text="LOINC code, e.g. '718-7' for Haemoglobin.", max_length=20)),
                ('snomed_code', models.CharField(blank=True, help_text='SNOMED CT concept code.', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=150)),
                ('specimen_type', models.CharField(choices=[('serum', 'Serum'), ('edta_whole_blood', 'EDTA Whole Blood'), ('blood_venous', 'Venous Whole Blood'), ('citrate', 'Citrate (coagulation)'), ('urine', 'Urine'), ('csf', 'CSF'), ('swab', 'Swab'), ('other', 'Other')], default='serum', max_length=30)),
                ('container_type', models.CharField(blank=True, max_length=100)),
                ('minimum_volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('result_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Free text'), ('coded', 'Coded (from value set)'), ('semi_quant', 'Semi-quantitative')], default='numeric', max_length=20)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('allowed_values', models.JSONField(blank=True, default=list, help_text="Allowed coded result values, e.g. ['Positive', 'Negative'].")),
                ('method', models.CharField(blank=True, max_length=200)),
                ('instrument', models.CharField(blank=True, max_length=200)),
                ('turnaround_hours', models.PositiveSmallIntegerField(blank=True, help_text='Routine turnaround time in hours.', null=True)),
                ('requires_validation', models.BooleanField(default=True, help_text='Result requires lab manager validation before release.')),
                ('reportable', models.BooleanField(default=True, help_text='Result is included in the patient report.')),
                ('requires_fasting', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Definition',
                'verbose_name_plural': 'Test Definitions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('instrument', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('precision_cv', models.DecimalField(blank=True, decimal_places=2, help_text='Coefficient of variation (%) for QC.', max_digits=6, null=True)),
                ('detection_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('linearity_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('linearity_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='catalog.labtestdefinition')),
            ],
            options={
                'verbose_name': 'Lab Test Method',
                'verbose_name_plural': 'Lab Test Methods',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text="Unique order code for this panel, e.g. 'FBC', 'CMP'.", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, help_text="Discipline label, e.g. 'Haematology', 'Biochemistry'.", max_length=150)),
                ('loinc_code', models.CharField(blank=True, help_text='LOINC panel code for interoperability.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Test Panel',
                'verbose_name_plural': 'Lab Test Panels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labtestdefinition',
            name='panel',
            field=models.ForeignKey(blank=True, help_text='Primary panel this test belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='catalog.labtestpanel'),
        ),
        migrations.AddField(
            model_name='labtestdefinition',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='catalog.measurementunit'),
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('any', 'Any / Not specified'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('age_min_days', models.PositiveIntegerField(blank=True, help_text='Minimum age in days (inclusive). Null = no lower bound.', null=True)),
                ('age_max_days', models.PositiveIntegerField(blank=True, help_text='Maximum age in days (exclusive). Null = no upper bound.', null=True)),
                ('label', models.CharField(blank=True, help_text="Human-readable label, e.g. 'Adult', 'Neonate', 'Pregnant'.", max_length=100)),
                ('low_normal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_normal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_critical', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_critical', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_reportable', models.DecimalField(blank=True, decimal_places=4, help_text='Lower limit of the analytical measurement range.', max_digits=12, null=True)),
                ('high_reportable', models.DecimalField(blank=True, decimal_places=4, help_text='Upper limit of the analytical measurement range.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='catalog.labtestdefinition')),
            ],
            options={
                'verbose_name': 'Reference Range',
                'verbose_name_plural': 'Reference Ranges',
                'ordering': ['test', 'gender', 'age_min_days'],
            },
        ),
        migrations.CreateModel(
            name='LabTestPanelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_optional', models.BooleanField(default=False)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.labtestpanel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_memberships', to='catalog.labtestdefinition')),
            ],
            options={
                'verbose_name': 'Panel Membership',
                'ordering': ['sort_order'],
                'unique_together': {('panel', 'test')},
            },
        ),
        migrations.AddIndex(
            model_name='labtestdefinition',
            index=models.Index(fields=['code'], name='catalog_lab_code_ed905a_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestdefinition',
            index=models.Index(fields=['loinc_code'], name='catalog_lab_loinc_c_5bd762_idx'),
        ),
    ]
