# Generated by Django 5.2.12 on 2026-04-02 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('family_name', models.CharField(db_index=True, help_text='Family / last name.', max_length=200)),
                ('given_names', models.CharField(help_text='Given (first + middle) names, space-separated.', max_length=300)),
                ('birth_date', models.DateField(db_index=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('deceased_date', models.DateField(blank=True, help_text='Date of death if applicable.', null=True)),
                ('id_patient', models.CharField(blank=True, db_index=True, help_text='Internal patient identifier assigned by the clinical system.', max_length=50, null=True, unique=True)),
                ('id_dream', models.CharField(blank=True, db_index=True, help_text='DREAM programme identifier for cross-system linkage.', max_length=50, null=True, unique=True)),
                ('caregiver_name', models.CharField(blank=True, help_text='Full name of primary caregiver or legal guardian.', max_length=300)),
                ('caregiver_contact', models.CharField(blank=True, help_text='Phone or email of the caregiver (free-text; use PatientContact for structured data).', max_length=300)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict, help_text='FHIR Address datatype stored as JSON.')),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='General clinical notes. Sensitive — access controlled.')),
                ('is_pregnant', models.BooleanField(blank=True, help_text='Current pregnancy status. Null = not applicable or unknown.', null=True)),
                ('is_breastfeeding', models.BooleanField(blank=True, help_text='Current breastfeeding status. Null = not applicable or unknown.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = inactive/merged patient. Not the same as soft-deleted.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility this patient record belongs to. Required in Phase 2.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='facilities.facility')),
                ('merged_into', models.ForeignKey(blank=True, help_text='If this patient record was merged, points to the surviving record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['family_name', 'given_names'],
            },
        ),
        migrations.CreateModel(
            name='DataConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('scope', models.CharField(choices=[('research', 'Research'), ('treatment', 'Treatment'), ('patient-privacy', 'Patient Privacy'), ('full', 'Full (Research + Treatment + Privacy)')], default='full', help_text='Scope of data processing covered by this consent.', max_length=30)),
                ('version', models.CharField(help_text="Consent form / document version (e.g. 'v2.1', '2024-01').", max_length=50)),
                ('consented_at', models.DateTimeField(help_text='Datetime when the patient signed / confirmed consent.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = consent has been revoked.')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Datetime when the consent was revoked.', null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason or reference for revocation (e.g. patient request, GDPR Art.7).')),
                ('collection_method', models.CharField(blank=True, help_text="How consent was obtained (e.g. 'paper', 'electronic', 'verbal').", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Staff member who collected the consent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_collected', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who processed the revocation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_revoked', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient this consent record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Data Consent',
                'verbose_name_plural': 'Data Consents',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('system', models.CharField(choices=[('phone', 'Phone'), ('fax', 'Fax'), ('email', 'Email'), ('sms', 'SMS'), ('other', 'Other')], default='phone', max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('use', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('mobile', 'Mobile'), ('old', 'Old')], default='home', max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='Preferred order (1 = highest priority).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Contact',
                'verbose_name_plural': 'Patient Contacts',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporary'), ('secondary', 'Secondary'), ('old', 'Old')], default='official', max_length=20)),
                ('system', models.CharField(help_text='URI identifying the namespace for the identifier value.', max_length=500)),
                ('value', models.CharField(db_index=True, help_text='The identifier value within the system.', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Identifier',
                'verbose_name_plural': 'Patient Identifiers',
                'ordering': ['system'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['family_name', 'birth_date'], name='patients_pa_family__d855d8_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconsent',
            index=models.Index(fields=['patient', 'is_active'], name='patients_da_patient_1f5e16_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconsent',
            index=models.Index(fields=['patient', 'scope', 'is_active'], name='patients_da_patient_08c83e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientidentifier',
            unique_together={('system', 'value')},
        ),
    ]
