# Generated by Django 5.2.12 on 2026-03-27 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this record has been soft-deleted.', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory reason for deletion (regulatory requirement).')),
                ('family_name', models.CharField(db_index=True, help_text='Family / last name.', max_length=200)),
                ('given_names', models.CharField(help_text='Given (first + middle) names, space-separated.', max_length=300)),
                ('birth_date', models.DateField(db_index=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('deceased_date', models.DateField(blank=True, help_text='Date of death if applicable.', null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict, help_text='FHIR Address datatype stored as JSON.')),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='General clinical notes. Sensitive — access controlled.')),
                ('is_active', models.BooleanField(default=True, help_text='False = inactive/merged patient. Not the same as soft-deleted.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility this patient record belongs to. Required in Phase 2.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='facilities.facility')),
                ('merged_into', models.ForeignKey(blank=True, help_text='If this patient record was merged, points to the surviving record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['family_name', 'given_names'],
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('phone', 'Phone'), ('fax', 'Fax'), ('email', 'Email'), ('sms', 'SMS'), ('other', 'Other')], default='phone', max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('use', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('mobile', 'Mobile'), ('old', 'Old')], default='home', max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='Preferred order (1 = highest priority).')),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Contact',
                'verbose_name_plural': 'Patient Contacts',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporary'), ('secondary', 'Secondary'), ('old', 'Old')], default='official', max_length=20)),
                ('system', models.CharField(help_text='URI identifying the namespace for the identifier value.', max_length=500)),
                ('value', models.CharField(db_index=True, help_text='The identifier value within the system.', max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Identifier',
                'verbose_name_plural': 'Patient Identifiers',
                'ordering': ['system'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['family_name', 'birth_date'], name='patients_pa_family__d855d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientidentifier',
            unique_together={('system', 'value')},
        ),
    ]
